development: &default
  enable_star: 1
  min_infix_len: 1

test:
  <<: *default
  mysql41: 9307

production:
  <<: *default
  pid_file: <%= YAML.load(`rails credentials:show`)['pid_file']['sphinx'] %>
